class CategoryResult {
  final String category;
  final double confidence;
  final String reason;

  CategoryResult({
    required this.category,
    required this.confidence,
    required this.reason,
  });
}

class CategoryService {
  static const List<String> standardCategories = [
    'Food',
    'Transport',
    'Shopping',
    'Bills',
    'Entertainment',
    'Health',
    'Education',
    'Travel',
    'Salary',
    'Investment',
    'Freelance',
    'Other',
  ];

  static final Map<String, List<String>> _keywordMap = {
    'Food': [
      'swiggy',
      'zomato',
      'mcdonalds',
      'kfc',
      'burger king',
      'starbucks',
      'cafe',
      'restaurant',
      'pizza',
      'dominos',
      'dine',
      'food',
      'bakery',
      'baker',
      'eats',
      'dining',
      'blinkit',
      'zepto',
      'instamart',
      'grocery',
      'supermarket',
      'subway',
      'chai',
      'tea',
      'coffee',
    ],
    'Transport': [
      'uber',
      'ola',
      'rapido',
      'metro',
      'fuel',
      'petrol',
      'diesel',
      'hpcl',
      'bpcl',
      'iocl',
      'indian oil',
      'toll',
      'fastag',
      'railway',
      'irctc',
      'parking',
      'bus',
      'cab',
      'taxi',
    ],
    'Shopping': [
      'amazon',
      'flipkart',
      'myntra',
      'ajio',
      'nykaa',
      'tata cliq',
      'zara',
      'h&m',
      'retail',
      'mart',
      'mall',
      'store',
      'clothing',
      'fashion',
      'electronics',
      'croma',
      'reliance digital',
      'meesho',
    ],
    'Bills': [
      'electricity',
      'bescom',
      'tneb',
      'mpeb',
      'uppcl',
      'water',
      'gas',
      'indane',
      'bharat gas',
      'hp gas',
      'internet',
      'wifi',
      'airtel',
      'jio',
      'vodafone',
      'vi',
      'recharge',
      'broadband',
      'dth',
      'tatasky',
      'maintenance',
      'rent',
      'bill',
      'utility',
    ],
    'Entertainment': [
      'netflix',
      'spotify',
      'prime video',
      'hotstar',
      'disney',
      'youtube',
      'movie',
      'cinema',
      'pvr',
      'inox',
      'bookmyshow',
      'gaming',
      'steam',
      'playstation',
      'xbox',
      'theatre',
      'concert',
      'apple music',
    ],
    'Health': [
      'pharmacy',
      'apollo',
      'medplus',
      '1mg',
      'pharmeasy',
      'hospital',
      'clinic',
      'doctor',
      'dental',
      'health',
      'medical',
      'medicine',
      'pathology',
      'diagnostic',
      'gym',
      'cult.fit',
      'fitness',
    ],
    'Education': [
      'udemy',
      'coursera',
      'tuition',
      'school',
      'college',
      'university',
      'books',
      'exam',
      'course',
      'class',
      'fee',
      'education',
      'academy',
    ],
    'Salary': [
      'salary',
      'payroll',
      'wages',
      'stipend',
      'bonus',
      'direct dep',
      'salary credit',
    ],
    'Investment': [
      'zerodha',
      'groww',
      'upstox',
      'angel one',
      'mutual fund',
      'sip',
      'dividend',
      'interest',
      'fd interest',
      'sebi',
      'nse',
      'bse',
      'coinbase',
      'binance',
    ],
  };

  static CategoryResult categorize(String description) {
    final clean = description.toLowerCase();

    for (final entry in _keywordMap.entries) {
      final category = entry.key;
      final keywords = entry.value;

      for (final kw in keywords) {
        if (clean.contains(kw)) {
          return CategoryResult(
            category: category,
            confidence: 0.92,
            reason: 'Matched "$kw"',
          );
        }
      }
    }

    return CategoryResult(
      category: 'Other',
      confidence: 0.4,
      reason: 'No keyword matched',
    );
  }
}
